# https://blog.mismithportfolio.com/web/netlify-cms
backend:
  name: git-gateway
  # name: github
  # repo: hkanako/netlify-cms-hugo
  branch: master

media_folder: "site/static/images/uploads"
public_folder: "/images/uploads"

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: "post"
    label: "Post"
    folder: "site/content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descreption", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
